import type { Metadata } from "next";
import { SidebarComponent } from "@/components/layout/sidbar";
import { MainContainer } from "@/components/layout/main-container";

export const metadata: Metadata = {
  title: "RecruitAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContainer>
      <SidebarComponent>{children}</SidebarComponent>
    </MainContainer>
  );
}
